Homework 5
ok-technopolis-2021/Dergunov_Nikita pull request #7
Opened 2021-11-30 19:08 UTC by nikita17th

2021-12-06 09:01 UTC, BusinessDuck requested changes

2021-12-06 09:01 UTC, BusinessDuck commented on dist/app.js
> +    constructor(name, ratio, id) {
У тебя есть Модель данных состощая из скилов, есть контроллер скилов, давай сделаем класс SkillView, который будет рисовать скилл, и все будет хорошо

2021-12-14 02:02 UTC, nikita17th commented
Я не совсем рахобрался как добавить import, когда добавляю gulp ругаться начинает, или собирает пустой js файл, погуглил нашел @rollup/plugin-node-resolve, но собрать тоже не удается (

2021-12-14 10:31 UTC, BusinessDuck commented on src/app.js
> +
Измени вид сборки в Rullup с esm на iife и разбей все на разные файлы. Сделай index.js или app.js файл как главный в котором будет слушаться событие DOMContentLoaded инициализироваться все остальное и в него импортируй все что нужно из остальных файлов

2021-12-14 10:31 UTC, BusinessDuck commented on src/app.js
> +        this.skillItem = document.createElement("section");
для справки еще есть такой подход https://developer.mozilla.org/ru/docs/Web/HTML/Element/template

2021-12-14 10:32 UTC, BusinessDuck approved these changes
Просто для справки всем кидаю мой костяк для реализации на ООП и некоторые пояснения про реактивность.  Может что-то почерпнешь для своей реализации. Переделывать не обязательно и так уже в целом неплохо выглядит!

Сейчас в основном применяется в разработке реактивный подход. Это когда состояние модели описано отдельно, а  UI изменяется в зависимости от изменения модели. То есть у тебя есть массив данных в нашем случае это скилы, в него добавляются или удаляются скилы, и в зависимости от вида манипуляции с моделью DOM реагирует на это и перестраивается, вот ниже пример как этого можно добиться. Однако будет ряд трудностей, во первых не понятно как грамотно перерисовывать содержимое, потому что может удалиться элемент в середине, и как-то нужно вычислить, какой это элемент и удалить его точечно, также элемент может добавиться в конец или в начало (не в нашем случае а в общем). Все эти перерисовки сложно управляемы. Эту задачу решают фреймоврки как раз.

В общем и целом, реактивных подход позволяет хранить данные модели отдельно, тем самым получая к ним доступ из любых мест приложения и делая его более гибким. Для отслеживания изменений в модели чаще всего используется паттерн Observer, ссылка и описание ниже.


Вот еще несколько примеров реализации от меня

```typescript
export class Skill {
    constructor(readonly name: string, readonly value: number) {}
}

export class SkillList {
    private list: Array<Skill>;

    constructor() {
        this.list = [];
    }

    add(skill: Skill) {
        this.list.push(skill);
    }

    remove(skill: Skill) {
        this.list.splice(this.list.indexOf(skill), 1);
    }
}

export class SkillView {
    constructor(private skill: Skill) {}

    render() {
        return this.HTML(`<div class="skill">${this.skill.name}<span>${this.skill.value}</span></div>`);
    }

    private HTML(str: string) {
        // @ts-ignore
        return repalceHtmlEntities(str);
    }
}

export class SkillListView {
    private list: Array<SkillView>;

    render() {
        return this.list.map(skill => skill.render()).join('');
    }
}

export class SkillListController {
    private skillList: SkillList;
    private skillListView: SkillListView;

    constructor(private target: Element) {...}

    addSkill(...) {
        // ...
        const skill = new Skill('123', 33);
        this.skillList.add(skill);
        this.target.innerHTML = this.skillListView.render();
    }
}

// index.ts

const target = document.querySelector('.target');
const skillController = new SkillListController(target);

// В идеале вообще использовать Observer Pattern

// index2.ts
const target = document.querySelector('.target');
const model = new SkillList();
const skillController = new SkillListController(target, model);

function addSkill() {
    model.push({ name: 'asdf', value: 33 });
}

function removeSkill(idx) {
    model.removeSkill(idx);
}

// И где-то внутри контроллера скилов
// Мы подписались на изменения модели, то есть при добавлении и удалении элемента вызовется коллбек. Паттерн 
 Observer можно посмотреть тут
https://monsterlessons.com/project/lessons/observer-pattern-v-javascript
this.model.subscribe((model => {});
```

2021-12-16 10:30 UTC, merged

2021-12-18 13:03 UTC, BusinessDuck reviewed
Баллы 40/40